In [43]:
import numpy as np
X = np.array([[1,1,2], [2,1,3], [3,1.2,1], [4,1,3], [5,0.8,2], [6,1,1]])
from sklearn.decomposition import NMF
model = NMF(n_components=3, init='random', random_state=0)
mm = model.fit(X)

In [38]:
W = mm.fit_transform(X)
W

array([[ 0.11974374,  0.58386684],
       [ 0.43732783,  0.80992528],
       [ 1.35345751,  0.19326676],
       [ 1.47131705,  0.690618  ],
       [ 2.18740815,  0.33083301],
       [ 2.90394818,  0.        ]])

In [39]:
mm.inverse_transform(W)

array([[ 1.03414659,  0.68685938,  2.08620216],
       [ 1.9955765 ,  1.04019292,  2.98899077],
       [ 3.0600072 ,  0.65072569,  1.15105453],
       [ 3.97372224,  1.24091879,  2.93368827],
       [ 4.97036614,  1.07220007,  1.92500241],
       [ 6.00693612,  0.93577167,  1.0178404 ]])

In [40]:
model.components_

array([[ 2.06854109,  0.32224117,  0.35050226],
       [ 1.34697107,  1.1103097 ,  3.50119506]])

In [45]:
model.reconstruction_err_

0.006608640993659931